-- MySQL Script generated by MySQL Workbench
-- Wed Dec 15 16:00:38 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema todo_app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema todo_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `todo_app` DEFAULT CHARACTER SET utf8 ;
USE `todo_app` ;

-- -----------------------------------------------------
-- Table `todo_app`.`prioridades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todo_app`.`prioridades` (
  `id_p` INT NOT NULL,
  `prioridad` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_p`),
  UNIQUE INDEX `Ninguna_UNIQUE` (`id_p` ASC),
  UNIQUE INDEX `Baja_UNIQUE` (`prioridad` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo_app`.`tareas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todo_app`.`tareas` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(25) NOT NULL,
  `descripcion` LONGTEXT NULL,
  `fecha_fin` DATE NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `hora_realizacion` TIME NOT NULL,
  `Prioridades_id_p` INT NOT NULL,
  `is_complete` TINYINT(0) NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `Id_tarea_UNIQUE` (`id_user` ASC),
  INDEX `fk_tareas_Prioridades1_idx` (`Prioridades_id_p` ASC),
  CONSTRAINT `fk_tareas_Prioridades1`
    FOREIGN KEY (`Prioridades_id_p`)
    REFERENCES `todo_app`.`prioridades` (`id_p`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo_app`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todo_app`.`usuarios` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(30) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` BINARY(20) NOT NULL,
  `confirm_password` BINARY(20) NOT NULL,
  `tareas_Id_tarea` INT NOT NULL,
  `creado` DATE NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  INDEX `fk_users_tareas1_idx` (`tareas_Id_tarea` ASC),
  CONSTRAINT `fk_users_tareas1`
    FOREIGN KEY (`tareas_Id_tarea`)
    REFERENCES `todo_app`.`tareas` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
